### PR TITLE
iCade fixes and support for tvOS

### PR DESCRIPTION
**Pull request by jasarien**

### CODE REVIEW

**Comment by jasarien** [comment]
@DanielFontes if you'd be willing to rebase your fork against master, I'd be happy to merge your stuff.

**Comment by appletv4** [comment]
One thing if possible since all icade controllers have a dedicated start and select button if you could remove start and select from the L and R shoulder buttons for NES GAMES 
I keep hitting L & R by accident on the nes30 controller while playing nes games

**Comment by stuartjmoore** [comment]
My gamepad is scheduled to arrive tomorrow night, so if this PR isn’t rebased, I’ll submit one similar.

**Comment by appletv4** [comment]
@stuartjmoore which controller did you get 

I got my second 8bitdo controller today an snes30 , feels much better than the nes30 
The nes controller is iconic but the snes is more  comfortable

**Comment by stuartjmoore** [comment]
My SFC30 (the colorful SNES controller) is charging now. I didn’t like the NES30 because it has more buttons than the original.

**Comment by pkamb** [comment]
I've rebased these changes on top of the latest master here: https://github.com/jasarien/Provenance/pull/493

**Comment by jasarien** [comment]
Closing in favour of @pkamb's request.

**Pull request closed without merging**
