### PR TITLE
Transfer roms and game saves between your device and computer easily over local network

### PR DESCRIPTION
**Pull request by dantheman213**
I have integrated a web server into Provenance that allows you to easily transfer ROMs and game saves between the app's document directory and your own computer through a special web page.

I have added an option to the settings allows you to start and stop the server and visit to begin the transfer process.

I also included a basic how to guide at the top of the web page when you visit it.

I did all necessary error checks to make sure it runs smoothly and I tried to keep the code as organized as possible.

This is the HTTP library I used for my implementation.
https://github.com/swisspol/GCDWebServer

I did extensive testing and it seems to work quite well. I think all users could benefit from this feature.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by jasarien** [comment]
Checking it out now :)

**Comment by jasarien** [comment]
I don't agree that this fixes rom searching or game library syncing. Searching the game library (which is #2 refers to) was implemented in a previous version and game library syncing is less about being able to upload/export roms/saves from a remote UI and more to do with keeping one to many devices in sync automatically, eg, dropbox sync.

However, I will merge this in as it is a pretty cool feature. Thanks.

**Comment by dantheman213** [comment]
I see your point there. This feature is more about a la carte bulk transfer or one-off transfer of saves to continue your adventure on PC or back onto your device. DropBox/Drive, cloud, etc would definitely be useful for en-masse up-to-date games against all devices.

Thanks! Glad you liked the addition.

I was thinking about potentially working on a way to implement Gameboy/Gameboy Advance link cable functionality over WiFi and/or bluetooth. I saw that done on a GBA emulator for Android. Have you thought of this and if so, had any luck?

**Comment by jasarien** [comment]
I haven't looked into doing that for GBA. GBA4iOS implemented it but never called it anything more than a beta. Provenance is using VBA for the GBA core and I think VBA did have that feature at some point, but I don't know how far diverged the version in Provenance is from the current. Feel free to look into it.

**Comment by tubartz08** [comment]
Hi! Im playing Suikoden 1 on PSX and i wanted to play suikoden 2 as sequel. The hardest part is, on battery save, it wont work. It says theres no save file from suikoden 1. provided that i copied save game from suikoden 1 folder in battery save file and paste it to suikoden 2 folder in battery save file. I am using ROMS with the same region (USA).

**Comment by jasarien** [comment]
When you paste the save file into the sequel’s save folder, you need to name it the same as one of it’s own MCR files. Easiest way to do this is to start a game in Suikoden 2 and make a save, copy its filename, then copy your Suikoden 1 save into the S2 folder using the filename of the S2 save.

**Pull request merged**
