### PR TITLE
Fixes iPhone 7 / 7 Plus random crashes

### PR DESCRIPTION
**Pull request by rafcabezas**
…the past

### CODE REVIEW

**Comment by lopeza511** [comment]
Seems to be working fine. I do get some lag every now and then. I am not sure if this was an issue before.

**Comment by rafcabezas** [comment]
@lopeza511 If you have a chance, please re-test (I moved the logic / refactoring).
Yes, I do see the lag; I believe this lag was causing the crashes before, now the game continues playing. I'm not sure if the lag exists on devices != iPhone7. But it might be worth some profiling. Definitely a different (but related) issue, though. (That is, this fix is not introducing this lag, rather, preventing it from crashing the phone).

**Comment by jasarien** [comment]
Seems to work ok as a temporary workaround for the issue at hand. I'll merge it while we continue looking for a more permanent solution.

**Comment by rafcabezas** [comment]
Sounds like a good plan!

**Pull request merged**
