### PR TITLE
Ability to Change Cover Art via Web Server’s UI

### PR DESCRIPTION
**Pull request by stuartjmoore**
Adds a directory watcher, similar to the ROMs directory watcher, that will import image file to matching game cover art.

> You can upload new cover art images by uploading a *.zip file into the Cover Art/ directory. The images need to be named the same as their ROM (IE, “kart fighter.nes.png” will update the artwork on “kart fighter.nes”. ROM Filenames can be found in the “com.provenance.*” directories). Then close the web server and Provenance will attempt to import them.

Issue #286

### CODE REVIEW

**Comment by Hanterdro** [comment]
Ehen this will be merged?

**Comment by jasarien** [comment]
When I get a chance

**Comment by lolkthxbai** [comment]
I've been testing this out for a while now and it works great. I was able to upload the photo to the directory and have provenance immediately detect and assign the image to the correct rom. I've only tried this with SNES roms but so far it's work great for all my roms missing their cover art.

**Comment by gareauk** [comment]
I've tried to do this and can't seem to import any covert art.  I created a folder called "Cover Art" and I renamed the images as described above and still a no go.

I'm using iOS 10.2.1 on a iPad Mini 4.

**Comment by jasarien** [comment]
It's not in the build you're using, @gareauk

**Pull request merged**
