### PR TITLE
Fix #255: Add Default TopShelf Image

### LINKED ISSUE #255: Official Top Shelf Icon tvOS
While this is technically not an issue, I feel that this topic fits here. I noticed that when I put Provenance on the top shelf, that there was no top shelf art work. So I made on: It contains screenshots of popular games for every console Provenance supports. Here it is, along with a screenshot. Think it could be the official Top Shelf artwork?
top shelf final
simulator screen shot dec 25 2015 3 12 16 pm

### PR DESCRIPTION
**Pull request by apexad**
This is the image from #255 created by PolarHacker added to the project.

### CODE REVIEW

**Comment by apexad** [comment]
@jasarien any issues with this pull request?  It is a very simple change, literally just adding an image in the TopShelf area.

**Comment by jasarien** [comment]
Honestly, I don't like the image.

**Comment by apexad** [comment]
Any thoughts on what a better image could look like?

I was thinking of doing something that incorporated the definition of the word Provenance with the addition of the screenshots like this one has, and dropping the controller overlay, since that is already in the icon.

**Comment by jasarien** [comment]
I'll close this PR. As mentioned I'm not a great fan of the image provided.

**Comment by appletv4** [comment]
hello @jasarien did you ever find an image you like ? iv been keeping provenance in my top row for a year and i can't get favorites working on the top shelf without a developer account , so an image would look better than a blank top shelf 

I've been using this one  from macrumors 
http://i.imgur.com/K8qmR3f.png
but an official one from you would be better

**Pull request closed without merging**
