### PR TITLE
Fix iCade

### PR DESCRIPTION
**Pull request by covertuser**
This should fix https://github.com/jasarien/Provenance/issues/228

### CODE REVIEW

**Comment by jasarien** [comment]
Awesome. I'll give a look when I get a spare moment. Did you manage to test it at all? I don't have iCade hardware to test with.

**Comment by jasarien** [comment]
The code looks sensible, but I'd like it if some people with iCade hardware could test this branch and let me know if it works. I can't merge it until it's been tested.

**Comment by pmp174** [comment]
@covertuser is it apple tv compatible

**Comment by covertuser** [comment]
I have not tested it on apple tv, so I don't know if it is atv compatible.  I was using this on an iphone 5/9.2.1 with an 8bitty controller.  When my xcode finished updating, I'll rebuild and give it a go with 9.3.

**Comment by pmp174** [comment]
hopefully it will work.

**Comment by pmp174** [comment]
I will try to test out it on my apple tv, in the meantime https://github.com/DanielFontes/Provenance made a branche which worked on the apple tv but only on debug mode. Maybe you can check it out.

**Comment by pmp174** [comment]
I tested it out on my steel series free and it does not work. It no longer crashes but the app doesn't respond to the controller.

**Comment by appletv4** [comment]
i have an apple tv,8bitdo controller and the new tvos 9.2, i can test this if you can add this to the apple tv ,in a separate branch

**Comment by asos-jamesaddyman** [comment]
@appletv4 just checkout @covertuser's fork and test it there.

**Comment by jasarien** [comment]
@appletv4 just checkout @covertuser's fork and test it there.

**Comment by kyuzumaki** [comment]
Tested on iPhone 5 with 8bitdo Zero. Works but you have to go to options and open and close the controller selection menu before the controller works.

**Comment by appletv4** [comment]
@jasarien I'm testing your current commit from an hour ago , with an sfc30 8bitdo controller 
On the Apple TV with the latest software 

I tried all the modes for the controller including icade & none work , the controller doesn't show up in settings/controller selection  

The Apple TV sees the controller as a keyboard , I can press buttons in the provenance search box with the 8bit controller and letters show up , so it is connected to the Apple TV

**Comment by jasarien** [comment]
There was no suggestion that iCade even works with tvOS. These iCade fixes are for iOS, not tvOS.

**Comment by josejulio** [comment]
@covertuser  Wow, thanks :+1:

**Comment by KULIK121** [comment]
@jasarien I am really new to this. Can you walk me through the process of how to get an 8bitdo nes30 pro controller working with Provenance for iOS?

**Comment by josejulio** [comment]
@KULIK121 You need to connect the controller to your iOS on iCade mode[1], go to settings on Provenance and there should be an option for iCade controller, choose one and that should do it.

[1] http://download.8bitdo.com/Manual/NES30_Pro_Manual_ENG_v1.0.pdf

**Comment by KULIK121** [comment]
Hello Again,
I have tried to connect the controller (8bitdo nes30 pro) to my iPad and I have been successful. When it comes to using the controller with the provenance I seem to be having a problem. In controller selection, I selected the player 1 line and the only option that I get is "not playing". I have also gone to the iCADE Controller setting and chosen my controller. Perhaps I am doing something wrong? The version I am running is 1.2.6 of provenance and I have also checked into updating the controller firmware. Is there something else I can do?

**Comment by KULIK121** [comment]
@jasarien I have tried to connect the controller (8bitdo nes30 pro) to my iPad and I have been successful. When it comes to using the controller with the provenance I seem to be having a problem. In controller selection, I selected the player 1 line and the only option that I get is "not playing". I have also gone to the iCADE Controller setting and chosen my controller. Perhaps I am doing something wrong? The version I am running is 1.2.6 of provenance and I have also checked into updating the controller firmware. Is there something else I can do?

**Comment by kyuzumaki** [comment]
Do not use 1.2.6 if you want to reliably use an iCade device. 1.2.5 is stable and will work.

If you really want to use 1.2.6 for some reason..In answer to the question you need to select iCade controller>8bitdo Nes30 then exit settings. Ignore the other option. Load a game it should now work. From my testing you need to re-select that each time you open the app and if it dosent work at first repeat the process.

Also are you sure its in iCade mode? To check just open up notes and hit some buttons you should see it typing letters.

**Comment by pjpalomaki** [comment]
Not only one character(letter) per button, but one character when you press the button and another when you release the button. If it only does a character when you press but not when you release, then you’re in BT keyboard mode, not in iCade mode. Am I right?

**Comment by josejulio** [comment]
@KULIK121 Can you try what @kyuzumaki @pjpalomaki said?
Could you confirm that you are indeed in iCade mode on your 8bitdo control?

**Comment by KULIK121** [comment]
@josejulio I have been trying to get provenance 1.2.5 installed on my Apple TV but it seems that I am having a problem with a "UIKeyboardHide" error. I have tried looking into the comments section but for some reason I guess I am not understanding how to fix it and get it installed/built. On another note, I have tried to utilize the other solutions and connected my 8bitdo nes30 pro controller to my Apple TV in iCADE mode but for some reason it does not seem to work currently with 1.2.6. When connected, I go into the setting and try to select the controller but it only gives me the option for the Apple TV remote. Is there something I am doing wrong?

**Comment by josejulio** [comment]
@KULIK121 Sorry, I don't have an Apple TV to test it. 
Is not there an "iCade controller" option on settings?

**Comment by KULIK121** [comment]
There is, however for some reason it does not appear to work when it is connected.

**Comment by kyuzumaki** [comment]
iCade does not work on Apple TV in any version of Provenance. This has already been explained earlier in the thread by @jasarien

**Comment by Hanterdro** [comment]
But after it's working on iOS it should be possible to add this feature to TVOS, too?
At least Apple TV accepts the Controllers in iCade Mode as a BlueTooth Keyboard :)

**Comment by kyuzumaki** [comment]
Yeah i think so keyboard support is part of 9.2 and you can definitely pair an iCade device. Just needs someone to implement it. If I get some spare time i'll have a go.

**Comment by polygon82** [comment]
@kyuzumaki
Just downloaded Provenance v1.2.6 and am trying to use the 8bitdo NES 30 controller in iCade mode. No problem pairing with my iPhone 6s in iCade mode (confirmed it was in iCade mode by typing in notepad; characters type both when I press a button and let go). But when in Provenance, I can't get it to register the device. I tried going into settings, selecting the 8bitdo and then exiting settings and going right into a game and nothing happens. Repeated as you mentioned earlier and still nothing. Is there anything else I can try? Is there a way to downgrade to Provenance v1.2.5? Super bummed because I've been dying to find a legit emulator on my iPhone that'll work with this controller. Thanks!

**Comment by apexad** [comment]
Assuming you are building Provenance yourself, try checking out this commit https://github.com/jasarien/Provenance/commit/9b95492882633e80b2bdb043fe8b57ec0467e206

It's sometime after that changes were made that adversely affected iCade controllers.  You'd be missing some other improvements surely, but if your controller works, there is not too much that would be worth not having that has been added lately.

**Comment by polygon82** [comment]
Nope, not building it myself. Literally just got the app working on my iPhone 6s, got a bunch of games downloaded, paired my 8bitdo NES 30 to my phone, but when I fire up Provenance the controller doesn't work. I'm able to select "8bitdo Nes30 Controller" from iCade controller but under Controller Selection all I can select is "Not Playing".

**Comment by josejulio** [comment]
I got 1.2.6 working on my phone, though installed some time ago.

**Comment by polygon82** [comment]
Provenance 1.2.6 itself works great!...I just can't get my sweet retro-looking NES controller to work with it. Touch screen controls blow.

**Comment by josejulio** [comment]
I meant to say that my NES30 pro controller works with that version.

Try what @kyuzumaki  said above:

> If you really want to use 1.2.6 for some reason..In answer to the question you need to select iCade controller>8bitdo Nes30 then exit settings. Ignore the other option. Load a game it should now work. From my testing you need to re-select that each time you open the app and if it dosent work at first repeat the process.

**Comment by polygon82** [comment]
@josejulio and @kyuzumaki

Ok so I went ahead and bought NES30 pro controller, updated the firmware, synced with my iPhone 6s no problem but still can't get anything to work with Provenance 1.2.6. I tried kyuzumaki's method and can't get anything to register either. I did notice that when I go to the menu once inside a game it gives me the option to disconnect the iCade device but I'm not actually able to use said device. Ugh! So frustrating! I just wanna play mega man 2 damnit! 

The only thing I can think of is maybe I could try finding a download of Provenance 1.2.5. Does anyone have any idea how I might accomplish this?

Thanks in advance!

**Comment by josejulio** [comment]
Are you able to compile Provenance? That would certainly work for either installing 1.2.5 or an iCade-working 1.2.6 version.

**Comment by polygon82** [comment]
Ya I don't really know how to do that. I'm a fast learner though! Any advice/documentation/resources you can recommend a programming beginner would be greatly appreciated!

**Comment by josejulio** [comment]
You don't need to program anything though, just download[1] last revision of Provenance and follow building instructions[2].

If the last doesn't work for you, you could try the 1.2.5 [3]

[1] https://github.com/jasarien/Provenance/archive/master.zip
[2] https://github.com/jasarien/Provenance/wiki/Building-Provenance
[3] https://github.com/jasarien/Provenance/archive/9b95492882633e80b2bdb043fe8b57ec0467e206.zip

**Comment by pmp174** [comment]
I'm sorry but what the fuck is wrong with provenance. This fake fix to icade, which took 6 months to   conjure after it had been broken, didn't actually fix anything except crashin. This was pushed 2 months ago and people are still complaining. I understand that developing this is difficult but provenance needs major restructuring because it has gotten so complicated that there are 55 issues and no one has been able to make a single move to fix them but everyone has a stupid comment to make on them, like that stupid perceivable latency one #157 . There is a problem with your app when people are referring to an older version of it to fix an issue. And all that will cause is more problems because people who download the older version may encounter bugs that have been fixed and report them further complicating the mattter. Its time to build provenance 2.0 because incremental fixes that slightly patch bugs aren't going to help this app. I apologize for the tone of my rant, but the constant notifications and lack of fixes are annoying.

**Comment by jasarien** [comment]
@pmp174 lol there's that entitlement again. 😂

The mounting issues and lack of progress recently is nothing to do with the complexity of Provenance's codebase, and I invite you to go ahead and review it for yourself if you're so confident in your own ability to improve on its 'complexity'. 

The lack of progress is purely down to the fact that I have had no time to work on it. Personal issues and "more important stuff" is currently taking priority in my life right now. 

You're aware that you're perfectly able to unsubscribe from the issues you're watching if the notifications are annoying you, right?😂

I'd appreciate it if next time you decide to rant you take a step back and think about what you're writing before posting it because I'm beholden to no-one when it comes to Provenance, and shouting things like "it's too complex" and "2.0 is needed" just prove how little you've actually looked at the code. 

All of the issues are fixable - given time. Now kindly get off your horse.

**Comment by jasarien** [comment]
@pmp174 I forgot to mention, feel free to submit a pull request with all the bug fixes you've done, and/or code restructuring that is so desperately needed. Currently none of the pull requests in the queue fix any of the 55 issues.

**Comment by apexad** [comment]
@jasarien I do think some of the pull requests do enough to close some of the issues (as some of them are mine, made to fix bugs reported in issues). Never the less though, there is certainly work that needs to be done from a code stand point and from an issue curating stand point as well. If you need any help with this, contact me, I can help.

@pmp174 I agree with @jasarien on this. Put up or shut up. Complaining and ranting does not help. Take that energy and passion and go learn some coding skills. Contribute to Provenance and other projects you use. Many other emulator projects for iPhone and Apple TV are completely abandoned by their authors. Be glad that @jasarien at least is a rove enough to respond to issues and contribute work to it.

Lastly, just want to say how great Provenance is for me and my SteelSeries Nimbus.

**Comment by Hanterdro** [comment]
@kyuzumaki 

Any news for the iCade TvOS implementation?
I would do it myself but I don't have any experience about Swift, C# or the Apple Frameworks :-/

**Comment by jasarien** [comment]
Neither Swift nor C# are used in Provenance 😂

**Comment by Hanterdro** [comment]
Maybe, I'm just a web-developer. I just do JS, CSS, Python and PHP :-)
And I meant Object C not C#. Object C was the precursor from Swift.

So Provenance is in Object C, right?
And more important, news about iCade for TvOS? :-)

**Comment by jasarien** [comment]
Object**ive** C, yeah. And no word on iCade from me. I don't have the hardware and no real interest in the feature itself. It's a community maintained feature. (In my opinion the MFi controllers are better, better supported by Apple in the SDK, have more choice to choose from and aren't much more expensive than iCade).

**Comment by Hanterdro** [comment]
Ok, I understand you POV.

But from a user perspective an iCade controller is better for e.g. SNES games  after you got this one:
http://www.8bitdo.com/sfc30/
I have also a MFi controller and it's absolutely no fun to play with a MFi Controller a SNES game. The Start and select Button are not very intuitive and it just don't feel right.

So I hope @kyuzumaki find some time to implement it.

**Comment by txcx** [comment]
anything new here? didn't seen that issue here.
tried to connect fc30 controller some minutes before (firmware v2.70) with provenance (v1.27) and same icade issues as above... works fine in other apps but not in this one :(

**Pull request merged**
