### PR TITLE
Added CRT shader and enabled 4K resolution for Apple TV 4K.

### PR DESCRIPTION
**Pull request by braindx**
The CRT shader used is one that I just wrote but I am releasing it into the public domain. It's heavily inspired by Timothy Lottes' shader, but that one is expensive to perform in a single pass and doesn't scale down well. I wanted something that was going to be performant on my Apple TV 4K and still look decent on my phone. Of course, now that it's hooked up, the shader can be replaced with whatever shader you want by replacing the contents of shader_crt_fragment.glsl. There are also a number of settings that can be tweaked at the top of the file.

CRT Filter can be enabled/disabled from the settings menu. It's off by default.

4K was enabled simply by adding a 2x launch image, not a big deal.

This pull request satisfies issue #54. Ideally, one could select from a list of shaders rather than just a single toggle, but it's a start.

### CODE REVIEW

**Comment by appletv4** [comment]
Been waiting 2 years for this , thanks 
@jasarien release the kraken

**Comment by appletv4** [comment]
Testing this now 
Btw they changed the way you choose a branch in Xcode 9 very confusing 

The crt filter looks and works great , is better with it on

**Comment by DanFessler** [comment]
just tested this locally myself and it runs and looks great.  Definitely think this should be merged in

**Comment by JoeMatt** [comment]
hm, I merged this branch into a testing branch on my fork and now it's showing my forks commits on this PR for some reason. I've done this method before, not sure what went wrong here.

**Comment by JoeMatt** [comment]
Did the same steps on #604 into my testing branch and that PR isn't showing my merge history. Not sure what happened here.

**Comment by jasarien** [comment]
@joe I’m a bit confused as to whether or not the mednafen PR included the CRT shader code or not.

**Pull request merged**
