### PR TITLE
Added support for iCade 8Bitdo SFC30 Controller

### PR DESCRIPTION
**Pull request by rafcabezas**
This probably also works for the 8Bitdo SNES30 Gamepad

### CODE REVIEW

**Comment by marcelvoss** [comment]
If so we should probably merge both 8Bitdo controllers into a single class.

**Comment by rafcabezas** [comment]
Good point, I'll work on that tomorrow. Feel free to merge this pull request in the mean time. I'll push a new one tomorrow, or as soon as I have free time.

**Comment by appletv4** [comment]
Will this work on tvOS or iOS only ?

**Comment by rafcabezas** [comment]
It should work on tvOS as well. But not tested.

**Comment by rafcabezas** [comment]
opening new one with the changes.

**Comment by leolobato** [comment]
tvOS doesn't support iCade controllers (including 8bitdo), unfortunately.

**Comment by rafcabezas** [comment]
Gotcha. Makes sense, actually.

**Pull request closed without merging**
