### PR TITLE
PSX Merge 2

### PR DESCRIPTION
**Pull request by apexad**

### CODE REVIEW

**Comment by apexad** [comment]
Sorry about this... I am working on getting PSX back in, meant to do this on my own fork.  I will create a new pull request when this is ready.

**Comment by apexad** [comment]
Just to be clear, I am no longer working on attempting to bring the PSX/Mednafen core into the current version of Provenance.

**Comment by pmp174** [comment]
Is there a reason like is it because of time constraints or is it too difficult with apples limitations? Just asking not trying to be pissy or anything.

**Comment by jasarien** [comment]
It's just tricky. Getting psx rearmed to compile in Xcode along with all its arm assembly bits for optimisations is plain difficult. The original project just has a make file and no Xcode project to base it on. My personal experience ended with me trying to figure out how to get Xcode to invoke the specific arm preprocessor tool that is required to make the assembly even compile. Effort + knowledge * time is what it boils down to and all are difficult to come by with spare-time projects like open source.

**Pull request closed without merging**
