### PR TITLE
New cores: Atari 2600, 7800 & Sega 32X

### PR DESCRIPTION
**Pull request by JoeMatt**
This branch is a fork of my stella branch.

It adds Atari7800, (ProSystem) and Sega 32X (Pico Drive)

32X has a couple issues. It crashes saving state on exit. The controller mapping maybe isn't the greatest as well but it's awkward to get the Sega 6 button layout into MFi ABXY plus shoulders. I suppose 

Tested on iPhone 6, iPad Air 2 and ATV. 32X will run choppy in debug builds but is full speed, can even run in 2X mode, in release builds.

I left the 32X core into this pull request despite the crashing issue on unload since it's trivial to disable by editing systems.plist. Maybe we could mark cores as Beta like OpenEMU does and indicate that in the library title for that system as well to allow users to test and report.

### CODE REVIEW

**Comment by Armored-Dragon** [comment]
PicoDrive doesn't compile for me. First, the header and Info.plist were missing, so I filled them in with ProSystem's and modif the impish to match. The compile got promising... until the end. The linker errored out with "unresolved symbols for architectures armv7". So I removed armv7 and armv7s from PicoDrive valid architectures, leaving just arm64. Plus, this build was only going to be used on my arm64 device anyway.

It looked promising, but still failed. The new error was also from the linker. It gave a bunch of undefined references, and an error suggesting the disabling of bitcode. I tried that, only to face another linker error saying I had to either disable bitcode for the entire project, or enable bitcode for this one. So that wasn't a solution.

Any help on this?

**Comment by JoeMatt** [comment]
What version of Xcode?

**Comment by Armored-Dragon** [comment]
Xcode 8, macOS Sierra GM, and iOS 10.0.1

**Comment by JoeMatt** [comment]
I've been out of town and I haven't tested with Xcode 8 since it went GM. I'll be updating this PR this week.

**Comment by Armored-Dragon** [comment]
OK, thanks.

**Comment by apexad** [comment]
Any progress on this @JoeMatt?  Would love to see this get merged for the Sega 32x support!

**Comment by JoeMatt** [comment]
It's being worked on. Haven't had time last few weeks. It'll be soon though.

**Comment by imseandavis** [comment]
Thanks for all your hard work @JoeMatt.

**Comment by appletv4** [comment]
@joematt with all these cores we going to need a way to change game consoles without scrolling up or down till we get to the console we want to play 

Change categories 

The entire Atari rom collection is like 5mb but that's a lot of scrolling

**Comment by JoeMatt** [comment]
Yes most likely the browser needs a redesign. 

I did add keyboard shortcut support to this branch in 4474f8a1dc4a55ded044d3ff92519da8519d577c 
If you have a bluetooth keyboard you can quickly access core and search features. Hold down Command to see the available shortcuts.

**Comment by JoeMatt** [comment]
I think only remaining bug is 32x, Start button doesn't work with on screen controls.

**Pull request merged**
