### PR TITLE
N64 support (mupen core)

### PR DESCRIPTION
**Pull request by braindx**
I've taken the awesome work of @JoeMatt integrating the mupen core into Provenance and took it the rest of the way toward getting it functional. Primarily, this involved adding support for cores that render directly to the GPU via OpenGL. This new render path renders to double-buffered textures and allows the rendering to take place in parallel on another thread. Additionally, I made some changes to force use of the pure interpreter (disabled dynarec and the cached interpreter), disabled some compiler optimizations in the interpreter that were causing issues, fixed up input (controller overlay, MFi gamepads, etc.), added support for restarting audio (needed for when N64 changes sample rates), fixed up deadlocks when loading/saving states, and fixed up a bunch of places where mupen didn't clean up properly after itself when shutting down.

I think this puts N64 emulation in a pretty decent state. Future work would likely include getting alternate plugins working like gliden64 to improve compatibility as I'm unsure what games work and how well.

### CODE REVIEW

**Comment by tonycoco** [comment]
Awesome work to you both.

**Comment by JoeMatt** [comment]
Switch to faster RspHLE and figured out what was causing clang to break optimisations on the machine code interpreter (kind of a big performance hit turning off optimisations) and switched to use the cached interpreter.

@braindx Further improved the GLES rendering code.
 
On Apple TV4,
Ocarina of Time went from ~45fps to full speed, MK Trilogy went from about 25 to full speed, as did a few others. There are occasional slow downs or audio glitching during cut scenes or some menus with texture blending, that might just be the Rice plugin. Looking into getting Gliden64 as that seems to be the new GFX plugin for Mupen with active development, Rice hasn't seen a real update in about 2 years. That's probably a bit down the road though. For now I'm happy with the performance, never believed it would run this well honestly.

**Comment by appletv4** [comment]
Joe can you test rush 2  n64 racing game

**Comment by pabloarista** [comment]
Tested out Mario 64, OOT, Majora's mask, and StarFox 64 on an iPhone 6+ and an iPad Pro 1 gen. Seems like European ROMS (50fps) runs perfect on both, but US ROMS (and I presume JP ROMs too) start to get laggy. Great work guys! I haven't installed this app on my dev apple TV so haven't tested that out.

**Comment by JoeMatt** [comment]
I just pushed a bunch more updates to the core so I'll go over them.
 I won't go over fixes, you can view them in the history if you are curious.

***
# The cool stuff #
## Added WebDav Server ##
I need the ability to upload folders, and the standard web interface didn't support this. I added a secondary web server for WebDav. 
This means you can how open a WebDav client to http://{ipaddress}:81  (or 8081 in simulator) and manage files without needing the web interface. 

**OS X has a built in WebDav client!** 
Simply from Finder hit Command+K (or Menubar -> Go -> Connect to Server...) and enter http://{ipaddress}:81 (Connect as guest)

**Finder will mount Provenance ROM folders as a drive!**
You can delete, rename, move, copy, and most importantly copy whole folders, which brings me too...

## Added hi-res texture pack support to N64 ##
The option is enabled by default since if it doesn't find textures for the current ROM nothing happens. 
To use hi-res texture packs you need to copy them to the directory `com.provenance.n64/hires_texture/{ROM NAME}`
The ROM NAME isn't the file name, but instead the identifier for the ROM in the header of the ROM file. If you don't know what it is, you can view the console output at load where it says something like,
`Mupen (3): Name: SUPER MARIO 64`
So in this example, if I wanted to load hi res textures for Mario 64 I would put them in,
`com.provenance.n64/hires_texture/SUPER MARIO 64`

Hi-Res packs come in folders with sub-folders. Just copy all the folders in the path as described above, mupen will find the right textures in sub folders.

Texture packs can be downloaded at [http://textures.emulation64.com/index.php?id=downloads](url)

For some reason this site splits larger texture packs into multiple zips. Just download all the zips and copy all their contents into the directory for your ROM as described above.

Hi-Res texture pack don't seem to noticeably degrade performance (on original ATV4 testing).
For me Mario 64 runs at 100% with dips here and there, and with the hi-res texture pack from [http://eazyhax.com/pitime/SUPER%20MARIO%2064.zip](url) and frame rates were the same as far as I could tell but visually everything was crisper. It seems that texture handling is not the bottle neck of performance for glupen64plus on iOS.

alt text

### Also on the web server... ###

- No longer disconnects when app is backgrounded
- Advertises itself on Bonjour

***
# Hacking Stuff #
### Added Video configuration defaults to MupenGameCore.m ###
In 'MupenGameCore.m' in the method 'loadFileAtPath' I added a number of settings for video that can be overridden. 

Currently all the settings are set to their defaults, expect the hires option since it's harmless without the files.

I did this to allow devs and users to modify options. For instance, those with more powerful devices like iPad Pro 2, iPhone 8,X, Apple TV 4K might want to enable some of the more advanced settings for video like AnisotropicFiltering, MipMapping or multi sampling for improved visual quality. These settings go well with the hi-res texture packs. I would recommend turning off the CRT filter in these cases too to see the differences.

***
# Nerdy / Tedious stuff #
### Upgraded main mupen64plus core to upstream ###
I guess it's good to be up to date. Not sure what exactly are the improvements or lack there of.

### Upgraded rsp-hle to upstream ###
This is the plugin the provides the functions for the Reality Coprocessor.
I updated to the current version available. I'm not sure if this made things better or in some ROMs added more glitching. I have to do more testing on this. This is most high performance, though somewhat dated and not most accurate RSP plugin available.

We were previously using RSPCDX4, but it was much slower. You can choose to use this by changing the line of code in `MupenGameCore.m` at the top of the file there's a line `#define USE_RSP_CXD4 0`.
Simply change the 0 to a 1 to try the alternate plugin.

### Fixed emulator unload (kind of) ###
I wasn't going to comment on bug fixes but this is more like a feature and needs some discussion.
Normally, the way multi-emulator frontends work, and even glupen64 with it's plugin design, when you load a game you dynamcally load the required code and unload it when. 

We switched from static libs to dynamic frameworks in our project around the time I started adding many more cores. On OS X we could weak link these frameworks and load them as we needed to load a game calling `dlopen` and unload them using `dlclose`. iOS is of course weird. For glupen we still use `dlopen` to load up the plugins and get references to exported functions we need to call, but when we call `dlclose` on those frameworks, iOS never actaully unloads the code or memory or calls any of the deconstructsors therefor for objects or frees pages for statics declared in the libraries. 

I did my best to divert from OpenEMU's code of simply not bothering to unload anything explicitly when they are done with a Mupen game, and copied retro arch's unload code. Plugins have to be specially disconnected, and then you have to find a pointer to their cleanup methods and call that before finally calling `dlclose`, which is do in vain since iOS doesn't actaully do anything useful with that call. 

This means after running mupen core, you're going to have a memory hit in the app, but not as bad as it was before. If you get low on memory, kill the app and restart, that's all we can do for now until Apple provides true weak linked frameworks on iOS (or if someone knows a hack).

### Updated the Web upload server ###
In general, any improvements to GCDWebServer are now beneficial to us.

***
# What's next #
_ In no particular order _
- [ ] Add a menu system to change the various Glupen video settings
- [ ] Possibly update the CXD4 RSP plugin since it might have some use
- [ ] Attempt to update to Rice 2.0 video plugin
- [ ] Start to look at GlideN64 video plugin

I'm way behind on some other projects now after going all in on Mupen following @braindx 's awesome  awesome work to get it all running smoothly. Big thanks to him to completing and more on what has taken me about year and a half of development on and off.

**Comment by Mr-se7enX** [comment]
@pabloarista. Did you test n64 games on ios 11? Did anyone compile N64 core for ios 11?

**Comment by pabloarista** [comment]
@Mr-se7enX yes, on my iPhone 6+ I have compiled and ran with iOS 11.2.2 without any issues.

**Comment by Mr-se7enX** [comment]
@pabloarista. Can you please send me the link for Compiled n64 core or at least the source you got it from.

**Comment by pabloarista** [comment]
@Mr-se7enX sure. On the top of this thread you can see the details, but you can go directly [here](https://github.com/braindx/Provenance). Don't forget it's the "mupen-rendering" branch. when you compile this, just use the same bundle ID to maintain all of your other ROMs/settings. I guess until there is a merge, this is the way to do it if you want to start testing

**Comment by Mr-se7enX** [comment]
@pabloarista. I can't build Provenance on ios 11 using Xcode 7. I have iOS 11 SDK inside Xcode 7. I don't have any problem building app to iOS 11 like RetroArch. I guess I need Provenance as an iPA file to install it. Is it possible to have N64 core to work with Retroarch emulator.

**Comment by jasarien** [comment]
@Mr-se7enX  If you want to use RetroArch, go to their repository and ask them.

**Comment by Mr-se7enX** [comment]
@jasarien. I  asked on their repository. Got no solution.

**Comment by jasarien** [comment]
Well, I’m afraid that’s their problem. As I said, this is for discussing the development of the N64 core. If you’re not able to compile it yourself in order to test it, then you will need to wait until it’s been tested and merged into the app and released. People don’t have time to build and package it at your request.

**Comment by pabloarista** [comment]
@Mr-se7enX the only thing I can tell you is what you're doing using Xcode 7 is more than likely a hack. As far as I can remember Xcode 7 doesn't work with iOS 11. It's NOT expected behavior in other words. Update to the latest Xcode and you won't have to do any hacks to make it work.

**Comment by Mr-se7enX** [comment]
Thanks @pabloarista, Im going to update to high sierra to install Xcode 9.

**Comment by pabloarista** [comment]
@Mr-se7enX you don't need High Sierra. I'm on the previous version (Sierra) without any issues. I think you need that as a minimum (in case you're in El Capitan).

**Comment by Mr-se7enX** [comment]
@pabloarista. yeah I'm in  El Capitan. I might go for Sierra. Thanks anyway.

**Comment by JoeMatt** [comment]
This PR has been merged into a feature branch along with a ton of additional improvements.
This should make it easier for others to checkout and build for themselves.

https://github.com/jasarien/Provenance/tree/feature/N64+Swift

**Comment by jasarien** [comment]
@JoeMatt  Curious: what happens to a PR if it gets merged into a feature branch? Should the PR stay open? Close it?

**Comment by JoeMatt** [comment]
No idea. Dealers choice I suppose. Can just close and not merge. It's merged outside of the GitHub system. There's no way to merge to another branch than the one that the PR was initiated on, I looked it up already.

**Comment by JoeMatt** [comment]
This branch could use some serious QA. A ton of things have been added or converted to Swift other than just N64 support.

Pretty much every feature has been touched in some way.

The only bug I know of right now is CD based ROMs don't import, new or using Reload library. Once I fix that I'm done with this branch.

**Comment by braindx** [comment]
Why in the world were all these unrelated N64 changes done on this branch? Can we separate out those commits?

**Comment by JoeMatt** [comment]
Because to fix thing X I had to do Y, and to do Y I wanted to do it in Swift. And then thing A, B and C just kept building on from there.

The original branch that this PR is built against isn't touched, it's still agnostic to my changes, but I fixed a bunch of other things too so why test them separately?

**Comment by braindx** [comment]
Because that's the point of Git branches, mainly. So that when feature addition X doesn't work we can still merge feature addition Y.

**Comment by JoeMatt** [comment]
It works that way when the changes are minor. These changes required changes to the workspace, project files, story boards etc. It's a major hassle to do all the changes. Like I said, the original PR branch is still the same, so git is still doing it's job just fine. This branch could be merge and my branch could merge on top of it too. I spend enough time on this as it is, I wasn't going to make 10 feature branches that all built on top of a common core Swift branch that changed the whole project structure.

**Comment by JoeMatt** [comment]
I also took a lot of care to group commits together and make sure, for the most part, that everything built between commits, so a buggy commit could be reverted if need be, it's not difficult. We don't have enough testers as it is, testing a ton of feature branches seems unlikely, better to do it all together and either fix those bugs or revert individual commits.

**Comment by braindx** [comment]
Okee

**Comment by JoeMatt** [comment]
When I said 'this branch needs major QA', I meant my fork of this branch too, should have been more clear, but there's not ticket associated with the other branch, and it's also confusing for users on how to check out from a different upstream server that the PR lives on (though there are instructions on the bottom of the page 'view command line instructions' it's not something most people can figure out.

**Comment by tonycoco** [comment]
Is feature/N64+Swift and braindx:mupen-rendering going to be kept in sync?

**Comment by braindx** [comment]
Moving forward, the most up-to-date branch for N64 support will now be the [feature/N64 branch](https://github.com/jasarien/Provenance/tree/feature/N64) until it is eventually merged into the development branch. If you pull it down and test it, let me know how you get on!

**Pull request closed without merging**
