### PR TITLE
Recent games

### PR DESCRIPTION
**Pull request by leolobato**
Recently played games section on library.

See #317

### CODE REVIEW

**Comment by tonycoco** [comment]
Oh, this is a great addition!

**Comment by jasarien** [comment]
Hey @leolobato, any chance you could sort out the conflicts here and then I'll give this a review. Thanks.

**Comment by leolobato** [comment]
@jasarien yep. I'll probably rebase my fork and re-apply these changes since I've also made some changes for #173 which would also raise other conflicts.

One question though: how many recent games should be visible? I thought:

- 12 on Apple TV (2 rows of games)
- 6 on iPhone (1 row on landscape, 2 on portrait)
- 9 on iPad (1 row on landscape, but it's not a full row on portrait, which only shows 7 games)

**Comment by jasarien** [comment]
Sounds good to me, I'll give it a try.

**Pull request merged**
