### PR TITLE
Stella (Atari 2600) support

### PR DESCRIPTION
**Pull request by JoeMatt**
ticket #187 

- Add stella (3.4.1 libretro variant)
- make PVSupport framework
- Added keyboard shortcuts to game library VC

### CODE REVIEW

**Comment by james-rantmedia** [comment]
Look like a big update. Awesome work. I'll check it out when I get some time.

**Comment by jasarien** [comment]
Looks like a big update. Awesome work. I'll check it out when I get some spare time.

**Comment by appletv4** [comment]
thanks joe

**Comment by hectorgarrofe** [comment]
Hello! I just tried Provenance on the AppleTV and it's perfect. Thanks for the great work!

Are you planning to update the main app in the near future?

I can help with non programming related issues.

Thanks.

**Comment by JoeMatt** [comment]
Closing in favor of PR #394

**Pull request closed without merging**
