### PR TITLE
Changes so that the FPS counter is based on emulation FPS, not openGL FPS.

### PR DESCRIPTION
**Pull request by rafcabezas**

### CODE REVIEW

**Comment by jasarien** [comment]
@rafcabezas could you solve the conflicts in this PR? I'll get around to merging it once its solved.

**Comment by rafcabezas** [comment]
I'll rebase asap

**Comment by appletv4** [comment]
@rafcabezas can you make the FPS numbers bigger ? You need a magnifying glass to see them on the tv , I'm sure on the iPhone is fine

**Comment by rafcabezas** [comment]
@appletv4 done: https://github.com/jasarien/Provenance/pull/511

**Pull request merged**
