### PR TITLE
Added ability to unzip rar and 7z formats.

### PR DESCRIPTION
**Pull request by tkunstek**
Added ability to unzip rar and 7z formats. Now also finds files in subdirectories of all archive types.

### CODE REVIEW

**Comment by JoeMatt** [comment]
In #566 I already added 7z through LzmaSDKObjC framework. It is missing RAR. I'd merge but there's a bunch of conflicts since I already added code paths for 7z.

**Comment by jasarien** [comment]
@tkunstek would it be possible to remove the 7z support from this PR so that it only includes RAR? Or are the two formats provided by the same lib?

**Comment by tkunstek** [comment]
Library used supports both formats. You can reject this PR and I'll come back through and add 7z separately.

**Comment by jasarien** [comment]
Just to clarify it’s the RAR support that needs adding separately - 7z was added with @Joe’a megaPR

**Comment by tkunstek** [comment]
Ah. I can still add RAR too if it will benefit someone.

**Comment by JoeMatt** [comment]
If this were to be added it would make sense to remove my LzmaSDKObjC dependency and depend on SARUnArchiveANY solely to reduce dependency management.

**Pull request closed without merging**
